# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20171014_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='flat_no',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
